# Copyright 2018 ACSONE SA/NV.
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from odoo import fields, models


class AccountMove(models.Model):
    _inherit = 'account.move'

    contract_id = fields.Many2one('contract.contract', string='Generated by contract', index=True,) #readonly=True) # with readonly=True there are not imported in import/export


