# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.15.0
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: OCB
odoo_version: 12.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: Modules for contracts management (recurring)
repo_name: Contract
repo_slug: contract
repo_website: https://github.com/OCA/contract

