# -*- coding: utf-8 -*-
# © 2016 Carlos Dauden <carlos.dauden@tecnativa.com>
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': 'Contract Invoice Merge By Partner',
    'summary': 'This module merges same partner invoices generated by '
               'contracts',
    'version': '8.0.1.0.0',
    'category': 'Account',
    'license': 'AGPL-3',
    'author': "Tecnativa, "
              "Odoo Community Association (OCA)",
    'website': 'http://www.tecnativa.com',
    'depends': ['account_analytic_analysis', 'account_invoice_merge'],
    'data': [
        'views/res_partner_view.xml',
    ],
    'installable': True,
}
