from . import partner_agreement
from . import agreement_clause
from . import agreement_section
from . import agreement_stage
from . import agreement_type
from . import agreement_subtype
from . import res_partner
from . import product_template
from . import agreement_renewaltype
from . import agreement_increasetype
