# -*- coding: utf-8 -*-
# © 2016 Carlos Dauden <carlos.dauden@tecnativa.com>
# © 2016 Pedro M. Baeza <pedro.baeza@tecnativa.com>
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from openerp import fields, models


class ResPartner(models.Model):
    _inherit = 'res.partner'

    contract_invoice_merge = fields.Boolean(
        string="Merge contracts invoices",
        help="If checked, all the recurring invoices generated by the "
             "contracts of this partner will be merged on each run.")
