[project]
name = "odoo-addons-oca-contract"
version = "19.0.20260904.0"
dependencies = [
    "odoo-addon-contract==19.0.*",
    "odoo-addon-contract_analytic_tag==19.0.*",
    "odoo-addon-contract_line_successor==19.0.*",
    "odoo-addon-contract_payment_mode==19.0.*",
    "odoo-addon-contract_sale==19.0.*",
    "odoo-addon-contract_update_last_date_invoiced==19.0.*",
    "odoo-addon-contract_variable_quantity==19.0.*",
    "odoo-addon-subscription_oca==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
